In [1]:
a=lambda a,b:a+b
c=a(10,23)
print(c)

33


In [22]:
s=lambda num:num%2==0
a=s(3)
if (a==True):
    print("even")
else:
    print("odd")

odd


In [26]:
x=int(input("enter number"))
s=lambda num:num%2==0
a=s(x)
if(a==True):
    print("even")
else:
    print("odd")

enter number56
even


In [29]:
def kamala(a,b):
    c=a+b
    return c
kamala(20,38)

58

a=10

In [35]:
a=int(input("enter number"))
def k1():
    print("first floor")
def k2():
    print("second floor")
def k3():
    print("third floor")
if(a==1):
    k1()
elif(a==2):
    k2()
else:
    k3()
    

enter number2
second floor


In [39]:
#no return no argument
def cool():
    a=int(input("enter number"))
    b=int(input("enter number"))
    c=a+b
    print(c)
cool()


enter number5
enter number5
10


In [41]:
#no r/arg
def c1(x,y):
    z=x*y
    print("product",z)
a=int(input("no:"))
b=int(input("no:"))
s=c1(a,b)


no:8
no:5
product 40


In [43]:
#r/no arg
def rol():
    a=int(input("enter number"))
    b=int(input("enter number"))
    c=a+b
    return c
a=rol()
print("sum:",a)  #function call in return

    
    


enter number5
enter number8
sum: 13


In [44]:
# ret/arg
def ew(x,y):
    z=x+y
    return z
a=int(input("enter number"))
b=int(input("enter number"))
s=ew(a,b)
print("sum",s)

enter number8
enter number10
sum 18


In [47]:
class kams:
    def fun(self,name,contact,loc):
        self.name=name
        self.contact=contact
        self.loc=loc
        print("name:",self.name)
        print("contact:",self.contact)
    def fun1(self):
        print("location",self.loc)
obj=kams()
obj.fun("kamal",9626545453,"dindigul")
obj.fun1()
        

name: kamal
contact: 9626545453
location dindigul


In [56]:
class op:
    def __init__(self,a,b):
        self.a=a
        self.b=b
    def fun(self):
        c=self.a+self.b
        return c
obj=op(56,85)
obj.fun()
        

141

In [55]:
class aa:
    def __init__(self,a,b):
        self.a=a
        self.b=b
        
    def fun(self):
        c=self.a+self.b
        print(c)
        
obj=aa(12,22)
obj.fun()

34


In [7]:
class con:
    def fun(self,a=None,b=None,c=None):
        if a!=None and b!=None and c!=None:
            print(a+b+c)
        elif a!=None and b!=None:
            print(a+b)
        else:
            print(a)
obj=con()
obj.fun(56,2)
        

58


In [13]:
class arf():
    def gf(self,*args):
        sum=0
        for i in args:
            sum+=i
        print(sum)
obj=arf()
obj.gf(4,3,4,5,858585858)

858585874


In [2]:
import numpy as np
import pandas as pd
a=np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
pd.Series([a])

0    [[1, 2, 3], [4, 5, 6]]
dtype: object

In [6]:
w=np.array([(1,2,3),("ss","ee","rr")])
w

array([['1', '2', '3'],
       ['ss', 'ee', 'rr']], dtype='<U11')

In [11]:
np.random.random(5)

array([0.18782548, 0.37430761, 0.24866561, 0.82361039, 0.57519516])

In [9]:
np.random.randn(3,3)

array([[ 0.24570528,  1.70466152,  1.34052694],
       [-0.5336945 , -0.80660626,  1.47830614],
       [-0.09634652, -1.22280549, -0.45179643]])

In [14]:
np.random.randint(10,50)

43

In [16]:
np.arange(10,100,10,float)

array([10., 20., 30., 40., 50., 60., 70., 80., 90.])

In [17]:
np.identity(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [19]:
np.eye(M=4,N=5)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [20]:
np.ones(2)

array([1., 1.])

In [23]:
np.empty((3,3),dtype=float)

array([[10., 20., 30.],
       [40., 50., 60.],
       [70., 80., 90.]])

In [24]:
np.full((5,5),fill_value=100,dtype=float)

array([[100., 100., 100., 100., 100.],
       [100., 100., 100., 100., 100.],
       [100., 100., 100., 100., 100.],
       [100., 100., 100., 100., 100.],
       [100., 100., 100., 100., 100.]])

In [31]:
np.linspace(100,1000,3)

array([ 100.,  550., 1000.])

In [32]:
a.shape

(2, 3)

In [33]:
a.ndim

2

In [34]:
np.mean(a)

3.5

In [35]:
a.size

6

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns


In [4]:
sns.get_dataset_names()

['anagrams',
 'anscombe',
 'attention',
 'brain_networks',
 'car_crashes',
 'diamonds',
 'dots',
 'dowjones',
 'exercise',
 'flights',
 'fmri',
 'geyser',
 'glue',
 'healthexp',
 'iris',
 'mpg',
 'penguins',
 'planets',
 'seaice',
 'taxis',
 'tips',
 'titanic']

In [5]:
#factorail of 
def fact(n):
    ou=1
    while n>0:
        ou*=n
        n-=1
    return ou
fact(5)

120

In [8]:

def fib(n):
    a=0
    b=1
    if n==0:
        print(a)
    elif n==1:
        print(a)
        print(b)
    elif n>1:
        print(a)
        print(b)
        for i in range(1,n-2):
            c=a+b
            print(c)
            a=b
            b=c
fib(10)
            
        

0
1
1
2
3
5
8
13
21


In [9]:
nu=992222222
int(str(nu)[::-1])

222222299

In [13]:
w=[10, 20, 30, 40, 50, 60, 70, 80, 90, 100]
for i in w[1::2]:
    print(i)

20
40
60
80
100


In [15]:
def cub(n):
    for i in range(1,n+1):
        print(i**3)
cub(4)

1
8
27
64


In [24]:
def ns(n):
    se=0
    ou=0
    for i in range(1,n):
        se=se*10+2
        ou+=se
    print(se)
    print(ou)
ns(5)

2222
2468


In [27]:
s=50
e=100
for i in range(s,e):
    for j in range(2,i):
        if i%j==0:
            break
    else:
        print(i)

53
59
61
67
71
73
79
83
89
97


In [29]:
for i in range(-10,0):
    print(i)
else:
    print("done")

-10
-9
-8
-7
-6
-5
-4
-3
-2
-1
done


In [31]:
l=[10, 20, 30, 40, 50]
op=[i for i in l[::-1]]
op

[50, 40, 30, 20, 10]

In [33]:
op.reverse()
op

[50, 40, 30, 20, 10]

In [35]:
d=[12, 75, 150, 180, 145, 525, 50]
for i in d:
    if i>500:
        break
    elif i>150:
        continue
    elif i%5==0:
        print(i)

75
150
145


In [41]:
def sum(n,m):
    ou=0
    for i in range(n,m+1):
        ou+=i
    print(ou)
sum(500,550)

26775


In [ ]:
a=1
while a<11:
    print(a)
    a+=1

In [ ]:
a=('kam','ala','kannan')
print(' '.join(a))

In [ ]:
def fact(n):
    for i in range(n):
        

In [6]:
from sklearn.datasets import fetch_california_housing
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [8]:
ds=fetch_california_housing()

In [12]:
print(ds.DESCR)

.. _california_housing_dataset:

California Housing dataset
--------------------------

**Data Set Characteristics:**

    :Number of Instances: 20640

    :Number of Attributes: 8 numeric, predictive attributes and the target

    :Attribute Information:
        - MedInc        median income in block group
        - HouseAge      median house age in block group
        - AveRooms      average number of rooms per household
        - AveBedrms     average number of bedrooms per household
        - Population    block group population
        - AveOccup      average number of household members
        - Latitude      block group latitude
        - Longitude     block group longitude

    :Missing Attribute Values: None

This dataset was obtained from the StatLib repository.
https://www.dcc.fc.up.pt/~ltorgo/Regression/cal_housing.html

The target variable is the median house value for California districts,
expressed in hundreds of thousands of dollars ($100,000).

This dataset was derived

In [19]:
df=pd.DataFrame(ds.data,columns=ds.feature_names)
df.head()

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0  8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1  8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2  7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3  5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4  3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   

   Longitude  
0    -122.23  
1    -122.22  
2    -122.24  
3    -122.25  
4    -122.25

In [17]:
ds.target

array([4.526, 3.585, 3.521, ..., 0.923, 0.847, 0.894])

In [21]:
df['Target']=ds.target

In [22]:
df.head()

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0  8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1  8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2  7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3  5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4  3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   

   Longitude  Target  
0    -122.23   4.526  
1    -122.22   3.585  
2    -122.24   3.521  
3    -122.25   3.413  
4    -122.25   3.422

In [23]:
X=df.iloc[:,:-1]
y=df.iloc[:,-1]

In [59]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.33,random_state=37)

In [60]:
sc=StandardScaler()

In [61]:
X_train=sc.fit_transform(X_train)

In [62]:
X_test=sc.transform(X_test)

In [63]:
X_test

array([[-1.3930278 ,  1.14270496, -0.52396261, ...,  0.11139806,
        -0.77048935,  0.65089742],
       [-0.36092962,  1.38080939, -0.03068062, ..., -0.060934  ,
        -0.72364659,  1.11949119],
       [-1.15515977, -0.60339418, -0.44521896, ..., -0.02806695,
         1.64191322, -1.01909101],
       ...,
       [-1.06107843,  0.26965539, -0.27325462, ..., -0.05792726,
         0.33499998, -0.03703811],
       [ 0.3425962 ,  0.34902353,  0.02295116, ..., -0.02907325,
         0.95332452, -0.70503349],
       [ 0.03734631,  0.82523239,  0.02553309, ..., -0.04337175,
         0.71442641, -1.2783131 ]])

In [64]:
from sklearn.linear_model import LinearRegression
lr=LinearRegression()

In [65]:
lr.fit(X_train,y_train)

LinearRegression()

In [66]:
y_pre=lr.predict(X_test)

In [67]:
from sklearn.metrics import r2_score
rc=r2_score(y_test,y_pre)
rc

0.6175745296165074

In [68]:
#display adjusted R-squared
1 - (1-rc)*(len(y)-1)/(len(y)-X.shape[1]-1)


0.6174262380279723

In [69]:
from sklearn.metrics import mean_squared_error,mean_absolute_error
mse=mean_squared_error(y_test,y_pre)
mae=mean_absolute_error(y_test,y_pre)
import numpy as np
print(np.sqrt(mse))
print(mae)


0.7109479534713654
0.528076524189442


In [70]:
from sklearn.linear_model import Ridge
rg=Ridge()
rg.fit(X_train,y_train)

Ridge()

In [71]:
rgp=rg.predict(X_test)

In [72]:
rgp

array([1.3285383 , 1.6497902 , 0.50758667, ..., 1.02424233, 2.07038396,
       2.7274788 ])

In [73]:
mse=mean_squared_error(y_test,rgp)
print(np.sqrt(mse))
mae=mean_absolute_error(y_test,rgp)
print(mae)

0.7109522652365573
0.5280707781022588


In [51]:
from sklearn.linear_model import Lasso
la=Lasso()
la.fit(X_train,y_train)

Lasso()

In [52]:
lap=la.predict(X_test)

In [53]:
lap

array([2.07034448, 2.07034448, 2.07034448, ..., 2.07034448, 2.07034448,
       2.07034448])

In [54]:
mse=mean_squared_error(y_test,lap)
print(np.sqrt(mse))
mae=mean_absolute_error(y_test,lap)
print(mse)

1.1553887530415143
1.3349231706548252
